namespace NMLServer;

internal enum KeywordType : byte
{
    None = 0,
    Grf,
    Param,
    Var,
    CargoTable,
    RailTypeTable,
    RoadTypeTable,
    TramTypeTable,
    If,
    Else,
    While,
    Item,
    Property,
    Graphics,
    LiveryOverride,
    SnowLine,
    BaseCost,
    Template,
    SpriteSet,
    Switch,
    String,
    SpriteGroup,
    RandomSwitch,
    Produce,
    Error,
    DisableItem,
    Replace,
    ReplaceNew,
    FontGlyph,
    Deactivate,
    TownNames,
    Return,
    TileLayout,
    SpriteLayout,
    AlternativeSprites,
    BaseGraphics,
    RecolourSprite,
    EngineOverride,
    Sort
}