namespace NMLServer;

internal enum KeywordType : byte
{
    None = 0,
    If,
    Grf,
    Var,
    Item,
    Else,
    Sort,
    While,
    Param,
    Error,
    Switch,
    Return,
    String,
    Produce,
    Replace,
    Property,
    SnowLine,
    BaseCost,
    Template,
    Graphics,
    TownNames,
    FontGlyph,
    SpriteSet,
    Deactivate,
    TileLayout,
    ReplaceNew,
    CargoTable,
    DisableItem,
    SpriteGroup,
    SpriteLayout,
    BaseGraphics,
    RandomSwitch,
    RailTypeTable,
    RoadTypeTable,
    TramTypeTable,
    RecolourSprite,
    EngineOverride,
    LiveryOverride,
    AlternativeSprites
}